[package]
name = "oxide_talis"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
p256 = { version = "0.13.2", features = ["ecdh"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
toml = "0.8.14"
